apiVersion: apps/v1
kind: Deployment            
metadata:
  name: buddy
  namespace: buddy-namespace
spec:
  replicas: 3             
  selector:
    matchLabels:
      app: buddy 
  template:             
    metadata:
      labels:          
        app: buddy 
    spec:                       
      containers:
      - name: buddy 
        image: vanillaketchup/buddy:1.0.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        livenessProbe:        
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:      
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1  
